version: '3'
services:
  db-teslo-shop-dev:
    image: postgres:14.3
    container_name: postgresql-teslo-shop-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-admin}
      POSTGRES_DB: ${DB_NAME:-NewBD}
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data